CREATE TABLE "lead_submissions" (
	"id" serial PRIMARY KEY NOT NULL,
	"lead_id" text NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"company" text,
	"email" text NOT NULL,
	"phone" text NOT NULL,
	"event_type" text NOT NULL,
	"event_date" text,
	"event_city" text,
	"event_postal_code" text,
	"estimated_value" text,
	"utm_source" text,
	"utm_medium" text,
	"utm_campaign" text,
	"utm_content" text,
	"utm_term" text,
	"gclid" text,
	"gbraid" text,
	"wbraid" text,
	"fbclid" text,
	"landing_page" text,
	"referrer" text,
	"crm_success" boolean DEFAULT false NOT NULL,
	"crm_status" integer,
	"email_sent" boolean DEFAULT false NOT NULL,
	"status" text DEFAULT 'lead' NOT NULL,
	"form_data" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "lead_submissions_lead_id_unique" UNIQUE("lead_id")
);
